<?php
//Gallery Controller Sidebar
?>
<script type="text/x-magento-init">
{
    ".gallery-controller": {
        "sliderPath":{
            "selector":".gallery-controller",
            "sliderOptions":{
                "slidesToShow": 3,
                "centerMode": false,
                "arrows": false,
                "dots":true,
                "responsive": [
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 1
                        }
                    }
                ]
            }
        }

    }
}
</script>
