<php
    /*Banner Slider*/
?>
<script type="text/x-magento-init">
    {
    ".baner": {
        "sliderPath": {
            "selector":".baner-wrapper",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "infinite": false,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
    }
</script>



<php
/*Our Products*/
?>
<script type="text/x-magento-init">
    {
    ".our_products": {
        "sliderPath": {
            "selector":".our_products .product-items",
            "sliderOptions":{
                "slidesToShow": 4,
                "slidesToScroll": 4,
                "infinite": false,
                "dots": false,
                "arrows": true,
                "autoplay": false,
                "autoplaySpeed": 5000,
                "responsive": [
                    {
                        "breakpoint": 1024,
                        "settings": {
                            "slidesToShow": 3,
                            "slidesToScroll": 3
                        }
                    },
                    {
                        "breakpoint": 768,
                        "settings": {
                            "slidesToShow": 2,
                            "slidesToScroll": 2
                        }
                    },
                    {
                        "breakpoint": 480,
                        "settings": {
                            "slidesToShow": 1,
                            "slidesToScroll": 1
                        }
                    }
                ]
            }
        }
    }
    }
</script>
