<?php
//Sidebar Slider
?>
<script type="text/x-magento-init">
{
    ".sidebar-slider": {
        "sliderPath": {
            "selector":".sidebar-slider",
            "sliderOptions":{
                "slidesToShow": 1,
                "slidesToScroll": 1,
                "dots": true,
                "arrows": false,
                "autoplay": true,
                "autoplaySpeed": 5000
            }
        }
    }
}
</script>

<?php
//Select for "Sort option"
?>
<script type="text/x-magento-init">
{
    ".toolbar-sorter": {
        "selectPath": {
            "selector":"#sorter",
            "sliderOptions":{}
        }
    }
}
</script>



