/*Main Banner*/
<div class="baner">
    <div class="container">
        <div class="container_text">
            <h1>cherner <span>armchair</span></h1>
            <h6>The 1958 moulded plywood armchair by Norman Cherner</h6>
            <a href="#">view now</a>
            <img src="https://i.ibb.co/f1xtbTM/bannerimg.png" alt="">
        </div>
        <img src="https://i.ibb.co/f1xtbTM/bannerimg.png" alt="">
    </div>
</div>
