/*Main Banner*/
<div class="baner">
    <div class="container">
        <div class="container_text">
            <h1>cherner <span>armchair</span></h1>
            <h6>The 1958 moulded plywood armchair by Norman Cherner</h6>
            <a href="#">view now</a>
            <img src="https://i.ibb.co/f1xtbTM/bannerimg.png" alt="">
        </div>
        <img src="https://i.ibb.co/f1xtbTM/bannerimg.png" alt="">
    </div>
</div>


/*Categories*/
<div class="categories">
    <div class="categories_container upon_all">
        <div class="cat_elem clock">
            <img src="https://i.ibb.co/0JsvNrN/clock.png"/>
            <div class="elem_textbox">
                <h1>Clocks</h1>
                <p>The 1958 moulded plywood armchair by Norman Cherner.</p>
                <a href="#">view now</a>
                <img src="https://i.ibb.co/0JsvNrN/clock.png"/>
            </div>
        </div>
        <div class="cat_elem lamp">
            <img src="https://i.ibb.co/M8SHWSq/lamp.png" alt="">
            <div class="elem_textbox">
                <h1><span>New</span> Lights</h1>
                <p>The 1958 moulded plywood armchair by Norman Cherner.</p>
                <a href="#">view now</a>
                <img src="https://i.ibb.co/M8SHWSq/lamp.png" alt="">
            </div>
        </div>
    </div>
</div>


/*November Sale*/
<div class="sale">
    <div class="upon_all sale_bg">
        <div class="sale_text">
            <div class="sale_info">
                <h2>november sale</h2>
                <h4>free shipping over $125 for international orders</h4>
            </div>
            <a href="#">shop now</a>
        </div>
    </div>
</div>
