/*Main Banner*/
<div class="baner">
    <div class="container">
        <div class="container_text">
            <h1>cherner <span>armchair</span></h1>
            <h6>The 1958 moulded plywood armchair by Norman Cherner</h6>
            <a href="#">view now</a>
            <img src="https://i.ibb.co/f1xtbTM/bannerimg.png" alt="">
        </div>
        <img src="https://i.ibb.co/f1xtbTM/bannerimg.png" alt="">
    </div>
</div>


/*Categories*/
<div class="categories">
    <div class="categories_container upon_all">
        <div class="cat_elem clock">
            <img src="https://i.ibb.co/0JsvNrN/clock.png"/>
            <div class="elem_textbox">
                <h1>Clocks</h1>
                <p>The 1958 moulded plywood armchair by Norman Cherner.</p>
                <a href="#">view now</a>
                <img src="https://i.ibb.co/0JsvNrN/clock.png"/>
            </div>
        </div>
        <div class="cat_elem lamp">
            <img src="https://i.ibb.co/M8SHWSq/lamp.png" alt="">
            <div class="elem_textbox">
                <h1><span>New</span> Lights</h1>
                <p>The 1958 moulded plywood armchair by Norman Cherner.</p>
                <a href="#">view now</a>
                <img src="https://i.ibb.co/M8SHWSq/lamp.png" alt="">
            </div>
        </div>
    </div>
</div>


/*Our Products*/
<div class="our_products upon_all">
    <div class="slider_btns product_slider_btns"><a href="#">Prev</a> <a href="#">Next</a></div>
    <div class="products_header">
        <h2>Our Products</h2>
        <h4>most trendy furniture</h4>
    </div>
    {{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="4" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`attribute_set_id`,`operator`:`==`,`value`:`15`^]^]"}}
</div>


/*November Sale*/
<div class="sale">
    <div class="upon_all sale_bg">
        <div class="sale_text">
            <div class="sale_info">
                <h2>november sale</h2>
                <h4>free shipping over $125 for international orders</h4>
            </div>
            <a href="#">shop now</a>
        </div>
    </div>
</div>



/*Bestsellers-Features-Most Viewed*/
<div class="products_group upon_all">
    <div class="group_item bestsellers">
        <span class="group_item_header">Bestsellers</span>
        <div class="group_item_content">{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="3" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`6`^]^]"}}</div>
    </div>
    <div class="group_item featured">
        <span class="group_item_header">Featured</span>
        <div class="group_item_content">{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="3" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`6`^]^]"}}</div>
    </div>
    <div class="group_item most_viewed">
        <span class="group_item_header">Most Viewed</span>
        <div class="group_item_content">{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" show_pager="0" products_count="3" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`6`^]^]"}}</div>
    </div>
</div>




/*News & Blog*/
<div class="news_blog upon_all">
    <div class="products_header">
        <h2>News & Blog</h2>
        <h4>most trendy furniture</h4>
    </div>
    <div class="news">
        <div class="news_item">
            <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/9/09_4.jpg"/>
            <h4>Aptent taciti soci litora cianpen</h4>
            <div class="news_date">
                <p class="far fa-calendar-alt"></p>
                <span>16-May-2017</span>
            </div>
            <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
        </div>
        <div class="news_item">
            <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/4/04_4.jpg"/>
            <h4>Mauris gravida nulla turpis</h4>
            <div class="news_date">
                <p class="far fa-calendar-alt"></p>
                <span>16-May-2017</span>
            </div>
            <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
        </div>
        <div class="news_item">
            <img src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/blog/images/0/3/03_4.jpg"/>
            <h4>Fusce gravida maximus elit</h4>
            <div class="news_date">
                <p class="far fa-calendar-alt"></p>
                <span>16-May-2017</span>
            </div>
            <p>Donec faucibus enim vitae volutpat sollicitudin. Mauris gravida nulla turpis, sit amet feugiat magna la</p>
        </div>
    </div>
</div>



/*Shop By Brands*/
<div class="brand_shop upon_all">
    <div class="shop_header">
        <span></span>
        <h1>Shop By Brands</h1>
        <span></span>
    </div>
    <div class="brand_icons">
        <div class="brand_icon">
            <a href="/knoll">
                <img alt="Knoll" src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/brand/brand2_af4945628435df11a3de0686bd9c4157.jpg"/>
            </a>
            <a href="/knoll">Knoll</a>
        </div>
        <div class="brand_icon">
            <a href="/herman-miller">
                <img alt="Herman Miller" src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/brand/brand3_5bba384c08d51704fbc44238fc1f075b.jpg"/>
            </a>
            <a href="/herman-miller">Herman Miller</a>
        </div>
        <div class="brand_icon">
            <a href="stressless">
                <img  alt="Stressless" src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/brand/brand5_7015ca7a49836d2461f226edc65db20b.jpg"/>
            </a>
            <a href="/stressless">Stressless</a>
        </div>
        <div class="brand_icon">
            <a href="/greenington">
                <img alt="Greenington" src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/brand/brand5_7015ca7a49836d2461f226edc65db20b.jpg"/>
            </a>
            <a href="/greenington">Greenington</a>
        </div>
        <div class="brand_icon">
            <a href="/younger">
                <img alt="Younger" src="https://blueskytechmage.com/drexel/pub/media/rokanthemes/brand/brand6_54f5ad48f6c2071a4f8793628d354b5b.jpg"/>
            </a>
            <a href="/younger">Younger</a>
        </div>
    </div>
</div>



/*Footer*/
