<?php
/**
 * @var $block \Mirasvit\Giftr\Block\Item\Add
 */
?>

<div class="giftr-list" style="display: none"
     data-bind="scope: 'giftr-addto__form'"
     data-mage-init='{"giftrPath":{}}'>

    <div class="registry-list" data-bind="visible: hasRegistries">
        <div class="registries options-container" data-bind="foreach: registries">
            <label for="registry_>" class="label option" data-bind="attr: { for: 'registry_' + value }">
                <input type="checkbox" id="registry_" name="registries[]" value=""
                       data-bind="checked: $parent.selected, value: value, attr: { id: 'registry_' + value }" />
                <span data-bind="text: label"></span>
            </label>
        </div>
        <div class="selected">
            Select Video Category
        </div>
        <a id="confirm-add-to-registry" href="#" data-bind="click: addProduct"><?= __('Add to Gift Registry') ?></a>
    </div>

    <div data-bind="visible: isMessageVisible()">
        <span data-bind="html: getMessage()"></span>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "customSelectPath": {
            "optionsContainer": ".options-container",
            "optionsList": ".option",
            "selected": ".selected"
        }
    }
}
</script>
