<?php
$helper = $this->helper(\Magento\Search\Helper\Data::class);
$configProvider = $block->getData('configProvider');

/*
Added JS widget for dropdown effect
*/
?>
<div class="block block-search" id="search-icon">
    <div class="block block-title"><strong><?= $block->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <em class="fa fa-search search-icon"></em>
    </div>
    <form class="form minisearch" id="search_mini_form"
          action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">
        <div class="field search">
            <label class="label" for="search" data-role="minisearch-label">
                <span><?= $block->escapeHtml(__('Search')) ?></span>
            </label>
            <div class="control">
                <input id="search"
                    <?php if ($configProvider->isSuggestionsAllowed()):?>
                        data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $block->escapeUrl($helper->getSuggestUrl())?>",
                                    "destinationSelector":"#search_autocomplete",
                                    "minSearchLength":"<?= $block->escapeHtml($helper->getMinQueryLength()) ?>"}
                               }'
                    <?php endif;?>
                       type="text"
                       name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                       value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                       placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
                       class="input-text"
                       maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                       role="combobox"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       autocomplete="off"
                       aria-expanded="false"/>
                <div id="search_autocomplete" class="search-autocomplete"></div>
                <?= $block->getChildHtml() ?>
            </div>

            <button type="submit"
                    title="<?= $block->escapeHtml(__('Search')) ?>"
                    class="action search"
                    aria-label="Search"
            >
                <span><?= $block->escapeHtml(__('Search')) ?></span>
            </button>
        </div>
    </form>
</div>


<script type="text/x-magento-init">
{
".search-icon": {
      "searchDropDown": {
        "dropElement": "#search_mini_form"
      }
    }
}
</script>
